# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='raft_service',
  syntax='proto3',
  serialized_options=b'\n\035io.grpc.examples.raft_serviceB\020RaftServiceProtoP\001\242\002\003RSP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x0craft_service\"0\n\x12\x43lientWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x88\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\t\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"5\n\x10\x43lientWriteReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08redirect\x18\x02 \x01(\t\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"5\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x32\x8c\x02\n\x0bRaftService\x12W\n\rAppendEntries\x12\".raft_service.AppendEntriesRequest\x1a .raft_service.AppendEntriesReply\"\x00\x12Q\n\x0bRequestVote\x12 .raft_service.RequestVoteRequest\x1a\x1e.raft_service.RequestVoteReply\"\x00\x12Q\n\x0b\x43lientWrite\x12 .raft_service.ClientWriteRequest\x1a\x1e.raft_service.ClientWriteReply\"\x00\x42\x39\n\x1dio.grpc.examples.raft_serviceB\x10RaftServiceProtoP\x01\xa2\x02\x03RSPb\x06proto3'
)




_CLIENTWRITEREQUEST = _descriptor.Descriptor(
  name='ClientWriteRequest',
  full_name='raft_service.ClientWriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='raft_service.ClientWriteRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='raft_service.ClientWriteRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=79,
)


_APPENDENTRIESREQUEST = _descriptor.Descriptor(
  name='AppendEntriesRequest',
  full_name='raft_service.AppendEntriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='raft_service.AppendEntriesRequest.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='raft_service.AppendEntriesRequest.leaderId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prevLogIndex', full_name='raft_service.AppendEntriesRequest.prevLogIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prevLogTerm', full_name='raft_service.AppendEntriesRequest.prevLogTerm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='raft_service.AppendEntriesRequest.entries', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaderCommit', full_name='raft_service.AppendEntriesRequest.leaderCommit', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=218,
)


_APPENDENTRIESREPLY = _descriptor.Descriptor(
  name='AppendEntriesReply',
  full_name='raft_service.AppendEntriesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='raft_service.AppendEntriesReply.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='raft_service.AppendEntriesReply.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=271,
)


_CLIENTWRITEREPLY = _descriptor.Descriptor(
  name='ClientWriteReply',
  full_name='raft_service.ClientWriteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='raft_service.ClientWriteReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='redirect', full_name='raft_service.ClientWriteReply.redirect', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=326,
)


_REQUESTVOTEREQUEST = _descriptor.Descriptor(
  name='RequestVoteRequest',
  full_name='raft_service.RequestVoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='raft_service.RequestVoteRequest.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='raft_service.RequestVoteRequest.candidateId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='raft_service.RequestVoteRequest.lastLogIndex', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='raft_service.RequestVoteRequest.lastLogTerm', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=426,
)


_REQUESTVOTEREPLY = _descriptor.Descriptor(
  name='RequestVoteReply',
  full_name='raft_service.RequestVoteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='raft_service.RequestVoteReply.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='raft_service.RequestVoteReply.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=481,
)

DESCRIPTOR.message_types_by_name['ClientWriteRequest'] = _CLIENTWRITEREQUEST
DESCRIPTOR.message_types_by_name['AppendEntriesRequest'] = _APPENDENTRIESREQUEST
DESCRIPTOR.message_types_by_name['AppendEntriesReply'] = _APPENDENTRIESREPLY
DESCRIPTOR.message_types_by_name['ClientWriteReply'] = _CLIENTWRITEREPLY
DESCRIPTOR.message_types_by_name['RequestVoteRequest'] = _REQUESTVOTEREQUEST
DESCRIPTOR.message_types_by_name['RequestVoteReply'] = _REQUESTVOTEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientWriteRequest = _reflection.GeneratedProtocolMessageType('ClientWriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTWRITEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.ClientWriteRequest)
  })
_sym_db.RegisterMessage(ClientWriteRequest)

AppendEntriesRequest = _reflection.GeneratedProtocolMessageType('AppendEntriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.AppendEntriesRequest)
  })
_sym_db.RegisterMessage(AppendEntriesRequest)

AppendEntriesReply = _reflection.GeneratedProtocolMessageType('AppendEntriesReply', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.AppendEntriesReply)
  })
_sym_db.RegisterMessage(AppendEntriesReply)

ClientWriteReply = _reflection.GeneratedProtocolMessageType('ClientWriteReply', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTWRITEREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.ClientWriteReply)
  })
_sym_db.RegisterMessage(ClientWriteReply)

RequestVoteRequest = _reflection.GeneratedProtocolMessageType('RequestVoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.RequestVoteRequest)
  })
_sym_db.RegisterMessage(RequestVoteRequest)

RequestVoteReply = _reflection.GeneratedProtocolMessageType('RequestVoteReply', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:raft_service.RequestVoteReply)
  })
_sym_db.RegisterMessage(RequestVoteReply)


DESCRIPTOR._options = None

_RAFTSERVICE = _descriptor.ServiceDescriptor(
  name='RaftService',
  full_name='raft_service.RaftService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=484,
  serialized_end=752,
  methods=[
  _descriptor.MethodDescriptor(
    name='AppendEntries',
    full_name='raft_service.RaftService.AppendEntries',
    index=0,
    containing_service=None,
    input_type=_APPENDENTRIESREQUEST,
    output_type=_APPENDENTRIESREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestVote',
    full_name='raft_service.RaftService.RequestVote',
    index=1,
    containing_service=None,
    input_type=_REQUESTVOTEREQUEST,
    output_type=_REQUESTVOTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClientWrite',
    full_name='raft_service.RaftService.ClientWrite',
    index=2,
    containing_service=None,
    input_type=_CLIENTWRITEREQUEST,
    output_type=_CLIENTWRITEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFTSERVICE)

DESCRIPTOR.services_by_name['RaftService'] = _RAFTSERVICE

# @@protoc_insertion_point(module_scope)
